# Generated by Django 4.2 on 2023-06-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPorta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_create',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(default=10000),
        ),
    ]
