# Generated by Django 4.2 on 2023-06-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPorta', '0002_curso_fecha_create_curso_fecha_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='fecha_create',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_update',
        ),
    ]
